export type GameResult = "W" | "L"

export type ScheduledGame = [
    opponent: string,
    result?: GameResult,
    score?: string
]

export type Schedule = {
    team: string
    conference: string
    week0?: ScheduledGame
    week1?: ScheduledGame
    week2?: ScheduledGame
    week3?: ScheduledGame
    week4?: ScheduledGame
    week5?: ScheduledGame
    week6?: ScheduledGame
    week7?: ScheduledGame
    week8?: ScheduledGame
    week9?: ScheduledGame
    week10?: ScheduledGame
    week11?: ScheduledGame
    week12?: ScheduledGame
}

export const schedules: Schedule[] = [
    {
        team: "NC State",
        conference: "ACC",
        week1: ["Virginia", "L", "8-34"],
        week2: ["FCS", "W", "73-0"],
        week3: ["Vanderbilt"],
        week4: ["App State"],
        week5: ["Louisville"],
        week6: ["Wake Forest"],
        week7: ["BYE"],
        week8: ["Stanford"],
        week9: ["California"],
        week10: ["Duke"],
        week11: ["Syracuse"],
        week12: ["Florida State"],
    },
    {
        team: "Florida State",
        conference: "ACC",
        week0: ["CUSA", "W", "34-17"],
        week1: ["SMU", "L", "24-27"],
        week2: ["BYE"],
        week3: ["Alabama"],
        week4: ["FCS"],
        week5: ["Virginia"],
        week6: ["Louisville"],
        week7: ["Miami FL"],
        week8: ["BYE"],
        week9: ["Clemson"],
        week10: ["Boston College"],
        week11: ["Pittsburgh"],
        week12: ["NC State"],
    },
    {
        team: "Louisville",
        conference: "ACC",
        week1: ["Mississippi", "L", "38-41"],
        week2: ["FCS", "W", "59-13"],
        week3: ["SMU"],
        week4: ["Wake Forest"],
        week5: ["NC State"],
        week6: ["Florida State"],
        week7: ["Syracuse"],
        week8: ["BYE"],
        week9: ["Stanford"],
        week10: ["Georgia Tech"],
        week11: ["North Carolina"],
        week12: ["Pittsburgh"],
    },
    {
        team: "Boston College",
        conference: "ACC",
        week1: ["Cincinnati", "L", "15-34"],
        week2: ["Rutgers", "W", "28-21"],
        week3: ["FCS"],
        week4: ["Virginia Tech"],
        week5: ["SMU"],
        week6: ["BYE"],
        week7: ["Pittsburgh"],
        week8: ["Georgia Tech"],
        week9: ["Duke"],
        week10: ["Florida State"],
        week11: ["Notre Dame"],
        week12: ["Syracuse"],
    },
    {
        team: "Miami",
        conference: "ACC",
        week1: ["Stanford", "W", "45-6"],
        week2: ["FCS", "W", "77-7"],
        week3: ["Wake Forest"],
        week4: ["MAC"],
        week5: ["Clemson"],
        week6: ["BYE"],
        week7: ["Florida State"],
        week8: ["Pittsburgh"],
        week9: ["North Carolina"],
        week10: ["Notre Dame"],
        week11: ["Duke"],
        week12: ["Virginia Tech"],
    },
    {
        team: "Wake Forest",
        conference: "ACC",
        week1: ["FCS", "W", "38-16"],
        week2: ["Purdue", "W", "38-36"],
        week3: ["Miami"],
        week4: ["Louisville"],
        week5: ["Stanford"],
        week6: ["NC State"],
        week7: ["California"],
        week8: ["BYE"],
        week9: ["Virginia"],
        week10: ["FCS"],
        week11: ["SMU"],
        week12: ["Georgia Tech"],
    },
    {
        team: "Virginia Tech",
        conference: "ACC",
        week1: ["FCS", "W", "73-3"],
        week2: ["Sun Belt", "W", "44-21"],
        week3: ["Maryland"],
        week4: ["Boston College"],
        week5: ["Pittsburgh"],
        week6: ["California"],
        week7: ["Georgia Tech"],
        week8: ["Clemson"],
        week9: ["BYE"],
        week10: ["SMU"],
        week11: ["Stanford"],
        week12: ["Miami"],
    },
    {
        team: "Georgia Tech",
        conference: "ACC",
        week1: ["Colorado", "L", "13-14"],
        week2: ["Tennessee", "L", "24-45"],
        week3: ["FCS"],
        week4: ["Stanford"],
        week5: ["BYE"],
        week6: ["Duke"],
        week7: ["Virginia Tech"],
        week8: ["Boston College"],
        week9: ["Pittsburgh"],
        week10: ["Louisville"],
        week11: ["Clemson"],
        week12: ["Wake Forest"],
    },
    {
        team: "SMU",
        conference: "ACC",
        week1: ["Florida State", "W", "27-24"],
        week2: ["FCS", "W", "56-10"],
        week3: ["Louisville"],
        week4: ["CUSA"],
        week5: ["Boston College"],
        week6: ["BYE"],
        week7: ["Virginia"],
        week8: ["California"],
        week9: ["Syracuse"],
        week10: ["Virginia Tech"],
        week11: ["Wake Forest"],
        week12: ["Notre Dame"],
    },
    {
        team: "Syracuse",
        conference: "ACC",
        week1: ["FCS", "W", "66-3"],
        week2: ["California", "L", "18-21"],
        week3: ["Pittsburgh"],
        week4: ["BYE"],
        week5: ["Independent"],
        week6: ["Virginia"],
        week7: ["Louisville"],
        week8: ["North Carolina"],
        week9: ["SMU"],
        week10: ["Clemson"],
        week11: ["NC State"],
        week12: ["Boston College"],
    },
    {
        team: "North Carolina",
        conference: "ACC",
        week1: ["TCU", "W", "15-10"],
        week2: ["FCS", "W", "35-3"],
        week3: ["Clemson"],
        week4: ["BYE"],
        week5: ["Notre Dame"],
        week6: ["Pittsburgh"],
        week7: ["Duke"],
        week8: ["Syracuse"],
        week9: ["Miami"],
        week10: ["Independent"],
        week11: ["Louisville"],
        week12: ["Virginia"],
    },
    {
        team: "Stanford",
        conference: "ACC",
        week0: ["MW", "W", "37-27"],
        week1: ["Miami", "L", "6-45"],
        week2: ["BYE"],
        week3: ["Duke"],
        week4: ["Georgia Tech"],
        week5: ["Wake Forest"],
        week6: ["Notre Dame"],
        week7: ["FCS"],
        week8: ["NC State"],
        week9: ["Louisville"],
        week10: ["BYE"],
        week11: ["Virginia Tech"],
        week12: ["California"],
    },
    {
        team: "Virginia",
        conference: "ACC",
        week1: ["NC State", "W", "34-8"],
        week2: ["FCS", "W", "59-3"],
        week3: ["West Virginia"],
        week4: ["CUSA"],
        week5: ["Florida State"],
        week6: ["Syracuse"],
        week7: ["SMU"],
        week8: ["Duke"],
        week9: ["Wake Forest"],
        week10: ["BYE"],
        week11: ["California"],
        week12: ["North Carolina"],
    },
    {
        team: "Clemson",
        conference: "ACC",
        week1: ["LSU", "L", "10-51"],
        week2: ["Sun Belt", "W", "22-7"],
        week3: ["North Carolina"],
        week4: ["California"],
        week5: ["Miami"],
        week6: ["BYE"],
        week7: ["FCS"],
        week8: ["Virginia Tech"],
        week9: ["Florida State"],
        week10: ["Syracuse"],
        week11: ["Georgia Tech"],
        week12: ["Duke"],
    },
    {
        team: "Pittsburgh",
        conference: "ACC",
        week1: ["MAC", "W", "59-14"],
        week2: ["UCF", "W", "12-7"],
        week3: ["Syracuse"],
        week4: ["FCS"],
        week5: ["Virginia Tech"],
        week6: ["North Carolina"],
        week7: ["Boston College"],
        week8: ["Miami"],
        week9: ["Georgia Tech"],
        week10: ["BYE"],
        week11: ["Florida State"],
        week12: ["Louisville"],
    },
    {
        team: "Duke",
        conference: "ACC",
        week1: ["AAC", "W", "17-3"],
        week2: ["Illinois", "W", "31-27"],
        week3: ["Stanford"],
        week4: ["FCS"],
        week5: ["BYE"],
        week6: ["Georgia Tech"],
        week7: ["North Carolina"],
        week8: ["Virginia"],
        week9: ["Boston College"],
        week10: ["NC State"],
        week11: ["Miami"],
        week12: ["Clemson"],
    },
    {
        team: "California",
        conference: "ACC",
        week1: ["UCLA", "L", "24-45"],
        week2: ["Syracuse", "W", "21-18"],
        week3: ["FCS"],
        week4: ["Clemson"],
        week5: ["MW"],
        week6: ["Virginia Tech"],
        week7: ["Wake Forest"],
        week8: ["SMU"],
        week9: ["NC State"],
        week10: ["BYE"],
        week11: ["Virginia"],
        week12: ["Stanford"],
    },
    {
        team: "Notre Dame",
        conference: "Independent",
        week1: ["Wisconsin", "W", "41-13"],
        week2: ["FCS", "W", "52-0"],
        week3: ["Michigan State"],
        week4: ["Purdue"],
        week5: ["North Carolina"],
        week6: ["Stanford"],
        week7: ["BYU"],
        week8: ["BYE"],
        week9: ["AAC"],
        week10: ["Miami"],
        week11: ["Boston College"],
        week12: ["SMU"],
    },
    {
        team: "Arizona State",
        conference: "Big 12",
        week1: ["FCS", "W", "70-7"],
        week2: ["Texas A&M"],
        week3: ["Kansas"],
        week4: ["BYE"],
        week5: ["Baylor"],
        week6: ["MW"],
        week7: ["Texas Tech"],
        week8: ["Kansas State"],
        week9: ["BYU"],
        week10: ["Colorado"],
        week11: ["UCF"],
        week12: ["Oklahoma State"],
    },
    {
        team: "Kansas State",
        conference: "Big 12",
        week1: ["FCS", "W", "71-3"],
        week2: ["PAC12", "W", "34-7"],
        week3: ["AAC"],
        week4: ["Cincinnati"],
        week5: ["BYE"],
        week6: ["Houston"],
        week7: ["Kansas"],
        week8: ["Arizona State"],
        week9: ["Colorado"],
        week10: ["Oklahoma State"],
        week11: ["TCU"],
        week12: ["Arizona"],
    },
    {
        team: "Texas Tech",
        conference: "Big 12",
        week1: ["FCS", "W", "33-10"],
        week2: ["PAC12", "W", "35-24"],
        week3: ["Houston"],
        week4: ["CUSA"],
        week5: ["Colorado"],
        week6: ["BYE"],
        week7: ["Arizona State"],
        week8: ["Cincinnati"],
        week9: ["Arizona"],
        week10: ["West Virginia"],
        week11: ["Oklahoma State"],
        week12: ["Baylor"],
    },
    {
        team: "Utah",
        conference: "Big 12",
        week1: ["FCS", "W", "66-14"],
        week2: ["Arkansas", "W", "43-10"],
        week3: ["PAC12"],
        week4: ["Iowa State"],
        week5: ["BYE"],
        week6: ["Kansas"],
        week7: ["Colorado"],
        week8: ["Houston"],
        week9: ["Cincinnati"],
        week10: ["BYU"],
        week11: ["Arizona"],
        week12: ["TCU"],
    },
    {
        team: "Houston",
        conference: "Big 12",
        week1: ["PAC12", "W", "33-20"],
        week2: ["FCS", "W", "77-6"],
        week3: ["Texas Tech"],
        week4: ["Sun Belt"],
        week5: ["UCF"],
        week6: ["Kansas State"],
        week7: ["Oklahoma State"],
        week8: ["Utah"],
        week9: ["BYE"],
        week10: ["Cincinnati"],
        week11: ["Colorado"],
        week12: ["West Virginia"],
    },
    {
        team: "Cincinnati",
        conference: "Big 12",
        week1: ["Boston College", "W", "34-15"],
        week2: ["FCS", "W", "62-10"],
        week3: ["MAC"],
        week4: ["Kansas State"],
        week5: ["Arizona"],
        week6: ["BYE"],
        week7: ["West Virginia"],
        week8: ["Texas Tech"],
        week9: ["Utah"],
        week10: ["Houston"],
        week11: ["Iowa State"],
        week12: ["Colorado"],
    },
    {
        team: "UCF",
        conference: "Big 12",
        week1: ["FCS", "W", "73-6"],
        week2: ["Pittsburgh", "L", "7-12"],
        week3: ["Sun Belt"],
        week4: ["TCU"],
        week5: ["Houston"],
        week6: ["Oklahoma State"],
        week7: ["BYE"],
        week8: ["BYU"],
        week9: ["Baylor"],
        week10: ["Kansas"],
        week11: ["Arizona State"],
        week12: ["Iowa State"],
    },
    {
        team: "BYU",
        conference: "Big 12",
        week1: ["FCS", "W", "63-7"],
        week2: ["Arizona", "W", "28-17"],
        week3: ["MW"],
        week4: ["BYE"],
        week5: ["TCU"],
        week6: ["Iowa State"],
        week7: ["Notre Dame"],
        week8: ["UCF"],
        week9: ["Arizona State"],
        week10: ["Utah"],
        week11: ["Baylor"],
        week12: ["Kansas"],
    },
    {
        team: "West Virginia",
        conference: "Big 12",
        week1: ["Sun Belt", "W", "31-24"],
        week2: ["FCS", "W", "52-7"],
        week3: ["Virginia"],
        week4: ["Oklahoma State"],
        week5: ["Iowa State"],
        week6: ["Arizona"],
        week7: ["Cincinnati"],
        week8: ["TCU"],
        week9: ["BYE"],
        week10: ["Texas Tech"],
        week11: ["Kansas"],
        week12: ["Houston"],
    },
    {
        team: "Baylor",
        conference: "Big 12",
        week1: ["Auburn", "L", "16-17"],
        week2: ["FCS", "W", "44-3"],
        week3: ["CUSA"],
        week4: ["Colorado"],
        week5: ["Arizona State"],
        week6: ["BYE"],
        week7: ["TCU"],
        week8: ["Kansas"],
        week9: ["UCF"],
        week10: ["Iowa State"],
        week11: ["BYU"],
        week12: ["Texas Tech"],
    },
    {
        team: "Arizona",
        conference: "Big 12",
        week1: ["FCS", "W", "35-7"],
        week2: ["BYU"],
        week3: ["MAC"],
        week4: ["PAC12"],
        week5: ["Cincinnati"],
        week6: ["West Virginia"],
        week7: ["BYE"],
        week8: ["Iowa State"],
        week9: ["Texas Tech"],
        week10: ["TCU"],
        week11: ["Utah"],
        week12: ["Kansas State"],
    },
    {
        team: "TCU",
        conference: "Big 12",
        week1: ["North Carolina", "L", "10-15"],
        week2: ["FCS", "W", "63-7"],
        week3: ["Sun Belt"],
        week4: ["UCF"],
        week5: ["BYU"],
        week6: ["BYE"],
        week7: ["Baylor"],
        week8: ["West Virginia"],
        week9: ["Kansas"],
        week10: ["Arizona"],
        week11: ["Kansas State"],
        week12: ["Utah"],
    },
    {
        team: "Colorado",
        conference: "Big 12",
        week1: ["Georgia Tech", "W", "14-13"],
        week2: ["FCS", "W", "52-21"],
        week3: ["Northwestern"],
        week4: ["Baylor"],
        week5: ["Texas Tech"],
        week6: ["BYE"],
        week7: ["Utah"],
        week8: ["Oklahoma State"],
        week9: ["Kansas State"],
        week10: ["Arizona State"],
        week11: ["Houston"],
        week12: ["Cincinnati"],
    },
    {
        team: "Kansas",
        conference: "Big 12",
        week1: ["FCS", "W", "51-6"],
        week2: ["Missouri", "L", "21-38"],
        week3: ["Arizona State"],
        week4: ["BYE"],
        week5: ["CUSA"],
        week6: ["Utah"],
        week7: ["Kansas State"],
        week8: ["Kansas"],
        week9: ["TCU"],
        week10: ["Baylor"],
        week11: ["West Virginia"],
        week12: ["BYU"],
    },
    {
        team: "Iowa State",
        conference: "Big 12",
        week1: ["FCS", "W", "38-10"],
        week2: ["Iowa", "L", "13-16"],
        week3: ["MAC"],
        week4: ["Utah"],
        week5: ["West Virginia"],
        week6: ["BYU"],
        week7: ["BYE"],
        week8: ["Arizona"],
        week9: ["Oklahoma State"],
        week10: ["Baylor"],
        week11: ["Cincinnati"],
        week12: ["UCF"],
    },
    {
        team: "Oklahoma State",
        conference: "Big 12",
        week1: ["CUSA", "L", "10-24"],
        week2: ["Oregon", "W", "39-31"],
        week3: ["FCS"],
        week4: ["West Virginia"],
        week5: ["BYE"],
        week6: ["UCF"],
        week7: ["Houston"],
        week8: ["Colorado"],
        week9: ["Iowa State"],
        week10: ["Kansas State"],
        week11: ["Oklahoma State"],
        week12: ["Arizona State"],
    },
    {
        team: "Michigan State",
        conference: "Big Ten",
        week1: ["MAC", "W", "30-20"],
        week2: ["MAC", "W", "35-7"],
        week3: ["Notre Dame"],
        week4: ["Nebraska"],
        week5: ["Wisconsin"],
        week6: ["Illinois"],
        week7: ["Northwestern"],
        week8: ["UCLA"],
        week9: ["BYE"],
        week10: ["Michigan"],
        week11: ["Washington"],
        week12: ["Oregon"],
    },
    {
        team: "Illinois",
        conference: "Big Ten",
        week1: ["AAC", "W", "42-23"],
        week2: ["Duke", "L", "27-31"],
        week3: ["FCS"],
        week4: ["Ohio State"],
        week5: ["Purdue"],
        week6: ["Michigan State"],
        week7: ["BYE"],
        week8: ["Oregon"],
        week9: ["Maryland"],
        week10: ["Nebraska"],
        week11: ["UCLA"],
        week12: ["Iowa"],
    },
    {
        team: "UCLA",
        conference: "Big Ten",
        week1: ["California", "W", "45-24"],
        week2: ["PAC12", "W", "28-10"],
        week3: ["Purdue"],
        week4: ["Maryland"],
        week5: ["BYE"],
        week6: ["Oregon"],
        week7: ["Wisconsin"],
        week8: ["Michigan State"],
        week9: ["MW"],
        week10: ["Minnesota"],
        week11: ["Illinois"],
        week12: ["Michigan"],
    },
    {
        team: "Purdue",
        conference: "Big Ten",
        week1: ["FCS", "W", "44-19"],
        week2: ["Wake Forest", "L", "36-38"],
        week3: ["UCLA"],
        week4: ["Notre Dame"],
        week5: ["Illinois"],
        week6: ["Minnesota"],
        week7: ["Washington"],
        week8: ["BYE"],
        week9: ["Penn State"],
        week10: ["Maryland"],
        week11: ["Iowa"],
        week12: ["Wisconsin"],
    },
    {
        team: "Oregon",
        conference: "Big Ten",
        week1: ["PAC12", "W", "34-27"],
        week2: ["Oklahoma State", "L", "31-39"],
        week3: ["FCS"],
        week4: ["USC"],
        week5: ["BYE"],
        week6: ["UCLA"],
        week7: ["Nebraska"],
        week8: ["Illinois"],
        week9: ["Northwestern"],
        week10: ["Ohio State"],
        week11: ["Michigan"],
        week12: ["Michigan State"],
    },
    {
        team: "Minnesota",
        conference: "Big Ten",
        week1: ["FCS", "W", "59-7"],
        week2: ["Mississippi State", "L", "13-38"],
        week3: ["MAC"],
        week4: ["Washington"],
        week5: ["Michigan"],
        week6: ["Purdue"],
        week7: ["BYE"],
        week8: ["Iowa"],
        week9: ["Indiana"],
        week10: ["UCLA"],
        week11: ["Penn State"],
        week12: ["Northwestern"],
    },
    {
        team: "Washington",
        conference: "Big Ten",
        week1: ["PAC12", "W", "24-10"],
        week2: ["PAC12", "W", "16-14"],
        week3: ["FCS"],
        week4: ["Minnesota"],
        week5: ["UCS"],
        week6: ["Iowa"],
        week7: ["Purdue"],
        week8: ["BYE"],
        week9: ["Nebraska"],
        week10: ["Penn State"],
        week11: ["Michigan State"],
        week12: ["Indiana"],
    },
    {
        team: "Wisconsin",
        conference: "Big Ten",
        week1: ["Notre Dame", "L", "13-41"],
        week2: ["FCS", "W", "36-9"],
        week3: ["MAC"],
        week4: ["Penn State"],
        week5: ["Michigan State"],
        week6: ["BYE"],
        week7: ["UCLA"],
        week8: ["USC"],
        week9: ["Iowa"],
        week10: ["Rutgers"],
        week11: ["Maryland"],
        week12: ["Purdue"],
    },
    {
        team: "Northwestern",
        conference: "Big Ten",
        week1: ["FCS", "W", "34-18"],
        week2: ["BYE"],
        week3: ["Colorado"],
        week4: ["Indiana"],
        week5: ["Penn State"],
        week6: ["MAC"],
        week7: ["Michigan State"],
        week8: ["Rutgers"],
        week9: ["Oregon"],
        week10: ["Iowa"],
        week11: ["Ohio State"],
        week12: ["Minnesota"],
    },
    {
        team: "USC",
        conference: "Big Ten",
        week0: ["MW", "W", "42-26"],
        week1: ["PAC12", "W", "39-0"],
        week2: ["Sun Belt", "W", "49-30"],
        week3: ["Rutgers"],
        week4: ["Oregon"],
        week5: ["Washington"],
        week6: ["Penn State"],
        week7: ["BYE"],
        week8: ["Wisconsin"],
        week9: ["Ohio State"],
        week10: ["BYE"],
        week11: ["Indiana"],
        week12: ["Maryland"],
    },
    {
        team: "Nebraska",
        conference: "Big Ten",
        week1: ["MAC", "W", "49-21"],
        week2: ["MAC", "W", "56-7"],
        week3: ["FCS"],
        week4: ["Michigan State"],
        week5: ["Maryland"],
        week6: ["Indiana"],
        week7: ["Oregon"],
        week8: ["BYE"],
        week9: ["Washington"],
        week10: ["Illinois"],
        week11: ["Rutgers"],
        week12: ["Ohio State"],
    },
    {
        team: "Ohio State",
        conference: "Big Ten",
        week1: ["MAC", "W", "56-3"],
        week2: ["Texas", "L", "23-24"],
        week3: ["MAC"],
        week4: ["Illinois"],
        week5: ["Iowa"],
        week6: ["Maryland"],
        week7: ["Indiana"],
        week8: ["BYE"],
        week9: ["USC"],
        week10: ["Oregon"],
        week11: ["Northwestern"],
        week12: ["Nebraska"],
    },
    {
        team: "Iowa",
        conference: "Big Ten",
        week1: ["MAC", "W", "40-0"],
        week2: ["Iowa State", "W", "16-13"],
        week3: ["FCS"],
        week4: ["Michigan"],
        week5: ["Ohio State"],
        week6: ["Washington"],
        week7: ["BYE"],
        week8: ["Minnesota"],
        week9: ["Wisconsin"],
        week10: ["Northwestern"],
        week11: ["Purdue"],
        week12: ["Illinois"],
    },
    {
        team: "Rutgers",
        conference: "Big Ten",
        week1: ["MAC", "L", "21-37"],
        week2: ["Boston College", "L", "21-28"],
        week3: ["USC"],
        week4: ["FCS"],
        week5: ["Indiana"],
        week6: ["BYE"],
        week7: ["Maryland"],
        week8: ["Northwestern"],
        week9: ["Michigan"],
        week10: ["Wisconsin"],
        week11: ["Nebraska"],
        week12: ["Penn State"],
    },
    {
        team: "Michigan",
        conference: "Big Ten",
        week1: ["MAC", "W", "13-12"],
        week2: ["Oklahoma", "W", "17-10"],
        week3: ["MW"],
        week4: ["Iowa"],
        week5: ["Minnesota"],
        week6: ["BYE"],
        week7: ["Penn State"],
        week8: ["Indiana"],
        week9: ["Rutgers"],
        week10: ["Michigan State"],
        week11: ["Oregon"],
        week12: ["UCLA"],
    },
    {
        team: "Maryland",
        conference: "Big Ten",
        week1: ["FCS", "W", "62-0"],
        week2: ["Independent", "W", "38-14"],
        week3: ["Virginia Tech"],
        week4: ["UCLA"],
        week5: ["Nebraska"],
        week6: ["Ohio State"],
        week7: ["Rutgers"],
        week8: ["BYE"],
        week9: ["Illinois"],
        week10: ["Purdue"],
        week11: ["Wisconsin"],
        week12: ["USC"],
    },
    {
        team: "Penn State",
        conference: "Big Ten",
        week1: ["Sun Belt", "W", "45-0"],
        week2: ["AAC", "W", "27-9"],
        week3: ["MAC"],
        week4: ["Wisconsin"],
        week5: ["Northwestern"],
        week6: ["USC"],
        week7: ["Michigan"],
        week8: ["BYE"],
        week9: ["Purdue"],
        week10: ["Washington"],
        week11: ["Minnesota"],
        week12: ["Rutgers"],
    },
    {
        team: "Indiana",
        conference: "Big Ten",
        week1: ["AAC", "W", "52-16"],
        week2: ["FCS", "W", "55-0"],
        week3: ["CUSA"],
        week4: ["Northwestern"],
        week5: ["Rutgers"],
        week6: ["Nebraska"],
        week7: ["Ohio State"],
        week8: ["Michigan"],
        week9: ["Minnesota"],
        week10: ["BYE"],
        week11: ["USC"],
        week12: ["Washington"],
    },
    {
        team: "Alabama",
        conference: "SEC",
        week1: ["CUSA", "W", "48-10"],
        week2: ["Kentucky", "W", "45-17"],
        week3: ["Florida State"],
        week4: ["South Carolina"],
        week5: ["Mississippi State"],
        week6: ["Georgia"],
        week7: ["Tennessee"],
        week8: ["Texas A&M"],
        week9: ["BYE"],
        week10: ["LSU"],
        week11: ["Vanderbilt"],
        week12: ["FCS"],
    },
    {
        team: "Oklahoma",
        conference: "SEC",
        week1: ["MW", "W", "51-0"],
        week2: ["Michigan", "L", "10-17"],
        week3: ["Sun Belt"],
        week4: ["Georgia"],
        week5: ["BYE"],
        week6: ["Texas"],
        week7: ["Kentucky"],
        week8: ["Mississippi State"],
        week9: ["South Carolina"],
        week10: ["Florida"],
        week11: ["Mississippi"],
        week12: ["Texas A&M"],
    },
    {
        team: "Georgia",
        conference: "SEC",
        week1: ["FCS", "W", "63-3"],
        week2: ["CUSA", "W", "70-20"],
        week3: ["Arkansas"],
        week4: ["Oklahoma"],
        week5: ["Vanderbilt"],
        week6: ["Alabama"],
        week7: ["Auburn"],
        week8: ["BYE"],
        week9: ["Florida"],
        week10: ["Mississippi"],
        week11: ["Missouri"],
        week12: ["South Carolina"],
    },
    {
        team: "Kentucky",
        conference: "SEC",
        week1: ["FCS", "W", "45-13"],
        week2: ["Alabama", "L", "17-45"],
        week3: ["Texas A&M"],
        week4: ["Sun Belt"],
        week5: ["South Carolina"],
        week6: ["LSU"],
        week7: ["Oklahoma"],
        week8: ["Vanderbilt"],
        week9: ["BYE"],
        week10: ["Tennessee"],
        week11: ["Florida"],
        week12: ["Missouri"],
    },
    {
        team: "Mississippi State",
        conference: "SEC",
        week1: ["Sun Belt", "W", "62-13"],
        week2: ["Minnesota", "W", "38-13"],
        week3: ["South Carolina"],
        week4: ["Missouri"],
        week5: ["Alabama"],
        week6: ["BYE"],
        week7: ["LSU"],
        week8: ["Oklahoma"],
        week9: ["Texas"],
        week10: ["Vanderbilt"],
        week11: ["Auburn"],
        week12: ["FCS"],
    },
    {
        team: "Missouri",
        conference: "SEC",
        week1: ["FCS", "W", "54-14"],
        week2: ["Kansas", "W", "38-21"],
        week3: ["Sun Belt"],
        week4: ["Mississippi State"],
        week5: ["Florida"],
        week6: ["Texas A&M"],
        week7: ["Mississippi"],
        week8: ["BYE"],
        week9: ["Arkansas"],
        week10: ["Texas"],
        week11: ["Georgia"],
        week12: ["Kentucky"],
    },
    {
        team: "South Carolina",
        conference: "SEC",
        week1: ["CUSA", "W", "57-0"],
        week2: ["FCS", "W", "45-9"],
        week3: ["Mississippi State"],
        week4: ["Alabama"],
        week5: ["Kentucky"],
        week6: ["Florida"],
        week7: ["BYE"],
        week8: ["Tennessee"],
        week9: ["Oklahoma"],
        week10: ["South Carolina"],
        week11: ["Arkansas"],
        week12: ["Georgia"],
    },
    {
        team: "Vanderbilt",
        conference: "SEC",
        week1: ["FCS", "W", "28-9"],
        week2: ["CUSA", "W", "35-26"],
        week3: ["NC State"],
        week4: ["Auburn"],
        week5: ["Georgia"],
        week6: ["Mississippi"],
        week7: ["Arkansas"],
        week8: ["Kentucky"],
        week9: ["BYE"],
        week10: ["Mississippi State"],
        week11: ["Alabama"],
        week12: ["Florida"],
    },
    {
        team: "Tennessee",
        conference: "SEC",
        week1: ["FCS", "W", "56-9"],
        week2: ["Georgia Tech", "W", "45-24"],
        week3: ["CUSA"],
        week4: ["Texas"],
        week5: ["Auburn"],
        week6: ["Arkansas"],
        week7: ["Alabama"],
        week8: ["South Carolina"],
        week9: ["BYE"],
        week10: ["Kentucky"],
        week11: ["Texas A&M"],
        week12: ["LSU"],
    },
    {
        team: "Texas",
        conference: "SEC",
        week1: ["PAC12", "W", "59-7"],
        week2: ["Ohio State", "W", "24-23"],
        week3: ["MW"],
        week4: ["Tennessee"],
        week5: ["BYE"],
        week6: ["Oklahoma"],
        week7: ["Florida"],
        week8: ["Mississippi"],
        week9: ["Mississippi State"],
        week10: ["Missouri"],
        week11: ["LSU"],
        week12: ["Arkansas"],
    },
    {
        team: "Florida",
        conference: "SEC",
        week1: ["AAC", "W", "66-21"],
        week2: ["FCS", "W", "52-3"],
        week3: ["Auburn"],
        week4: ["Mississippi"],
        week5: ["Missouri"],
        week6: ["South Carolina"],
        week7: ["Texas"],
        week8: ["BYE"],
        week9: ["Georgia"],
        week10: ["Oklahoma"],
        week11: ["Kentucky"],
        week12: ["Vanderbilt"],
    },
    {
        team: "Texas A&M",
        conference: "SEC",
        week1: ["CUSA", "W", "50-0"],
        week2: ["Arizona State", "W", "48-20"],
        week3: ["Kentucky"],
        week4: ["LSU"],
        week5: ["Arkansas"],
        week6: ["Missouri"],
        week7: ["FCS"],
        week8: ["Alabama"],
        week9: ["BYE"],
        week10: ["South Carolina"],
        week11: ["Tennessee"],
        week12: ["Oklahoma"],
    },
    {
        team: "Mississippi",
        conference: "SEC",
        week1: ["Louisville", "W", "41-38"],
        week2: ["AAC", "W", "41-9"],
        week3: ["LSU"],
        week4: ["Florida"],
        week5: ["BYE"],
        week6: ["Vanderbilt"],
        week7: ["Missouri"],
        week8: ["Texas"],
        week9: ["Auburn"],
        week10: ["Georgia"],
        week11: ["Oklahoma"],
        week12: ["FCS"],
    },
    {
        team: "Auburn",
        conference: "SEC",
        week1: ["Baylor", "W", "17-16"],
        week2: ["Sun Belt", "W", "43-8"],
        week3: ["Florida"],
        week4: ["Vanderbilt"],
        week5: ["Tennessee"],
        week6: ["BYE"],
        week7: ["Georgia"],
        week8: ["LSU"],
        week9: ["Mississippi"],
        week10: ["Arkansas"],
        week11: ["Mississippi State"],
        week12: ["FCS"],
    },
    {
        team: "LSU",
        conference: "SEC",
        week1: ["Clemson", "W", "51-10"],
        week2: ["Sun Belt", "W", "45-14"],
        week3: ["Mississippi"],
        week4: ["Texas A&M"],
        week5: ["FCS"],
        week6: ["Kentucky"],
        week7: ["Mississippi State"],
        week8: ["Auburn"],
        week9: ["BYE"],
        week10: ["Alabama"],
        week11: ["Texas"],
        week12: ["Tennessee"],
    },
    {
        team: "Arkansas",
        conference: "SEC",
        week1: ["FCS", "W", "31-14"],
        week2: ["Utah", "L", "10-43"],
        week3: ["Georgia"],
        week4: ["AAC"],
        week5: ["Texas A&M"],
        week6: ["Tennessee"],
        week7: ["Vanderbilt"],
        week8: ["BYE"],
        week9: ["Missouri"],
        week10: ["Auburn"],
        week11: ["South Carolina"],
        week12: ["Texas"],
    },
]

export function getTeamSchedule(teamName: string): Schedule | undefined {
    return schedules.find(
        (schedule) =>
            schedule.team.toLowerCase() === teamName.toLowerCase()
    )
}

export function getTeamOpponent(teamName: string, week: number): string | undefined {
    const schedule = getTeamSchedule(teamName)

    if (!schedule) {
        return undefined
    }

    const weekKey = `week${week}` as keyof Schedule
    const game = schedule[weekKey]

    if (!Array.isArray(game)) {
        return undefined
    }

    return game[0]
}

export function getTeamGame(teamName: string, week: number): ScheduledGame | undefined {
    const schedule = schedules.find(
        (item) => item.team === teamName
    )

    if (!schedule) {
        return undefined
    }

    const weekKey = `week${week}` as keyof Schedule
    const game = schedule[weekKey]

    return Array.isArray(game) ? game as ScheduledGame : undefined
}