export type Schedule = {
    team: string;
    conference: string;
    week1?: string;
    week2?: string;
    week3?: string;
    week4?: string;
    week5?: string;
    week6?: string;
    week7?: string;
    week8?: string;
    week9?: string;
    week10?: string;
    week11?: string;
    week12?: string;
}

export const schedules: Schedule[] = [
    {
        team: "NC State",
        conference: "ACC",
        week1: "Virginia",
        week2: "FCS",
        week3: "Vanderbilt",
        week4: "App State",
        week5: "Louisville",
        week6: "Wake Forest",
        week7: "BYE",
        week8: "Stanford",
        week9: "California",
        week10: "Duke",
        week11: "Syracuse",
        week12: "Florida State",
    },
    {
        team: "Florida State",
        conference: "ACC",
        week1: "SMU",
        week2: "BYE",
        week3: "Alabama",
        week4: "FCS",
        week5: "Virginia",
        week6: "Louisville",
        week7: "Miami FL",
        week8: "BYE",
        week9: "Clemson",
        week10: "Boston College",
        week11: "Pittsburgh",
        week12: "NC State",
    },
    {
        team: "Louisville",
        conference: "ACC",
        week1: "Mississippi",
        week2: "FCS",
        week3: "SMU",
        week4: "Wake Forest",
        week5: "NC State",
        week6: "Florida State",
        week7: "Syracuse",
        week8: "BYE",
        week9: "Stanford",
        week10: "Georgia Tech",
        week11: "UNC",
        week12: "Pittsburgh",
    },
    {
        team: "Boston College",
        conference: "ACC",
        week1: "Cincinnati",
        week2: "Rutgers",
        week3: "FCS",
        week4: "Virginia Tech",
        week5: "SMU",
        week6: "BYE",
        week7: "Pittsburgh",
        week8: "Georgia Tech",
        week9: "Duke",
        week10: "Florida State",
        week11: "Notre Dame",
        week12: "Syracuse",
    },
    {
        team: "Miami",
        conference: "ACC",
        week1: "Stanford",
        week2: "FCS",
        week3: "Wake Forest",
        week4: "MAC",
        week5: "Clemson",
        week6: "BYE",
        week7: "Florida State",
        week8: "Pittsburgh",
        week9: "UNC",
        week10: "Notre Dame",
        week11: "Duke",
        week12: "Virginia Tech",
    },
    {
        team: "Wake Forest",
        conference: "ACC",
        week1: "FCS",
        week2: "Purdue",
        week3: "Miami",
        week4: "Louisville",
        week5: "Stanford",
        week6: "NC State",
        week7: "California",
        week8: "BYE",
        week9: "Virginia",
        week10: "FCS",
        week11: "SMU",
        week12: "Georgia Tech",
    },
    {
        team: "Virginia Tech",
        conference: "ACC",
        week1: "FCS",
        week2: "Sun Belt",
        week3: "Maryland",
        week4: "Boston College",
        week5: "Pittsburgh",
        week6: "California",
        week7: "Georgia Tech",
        week8: "Clemson",
        week9: "BYE",
        week10: "SMU",
        week11: "Stanford",
        week12: "Miami",
    },
    {
        team: "Georgia Tech",
        conference: "ACC",
        week1: "Colorado",
        week2: "Tennessee",
        week3: "FCS",
        week4: "Stanford",
        week5: "BYE",
        week6: "Duke",
        week7: "Virginia Tech",
        week8: "Boston College",
        week9: "Pittsburgh",
        week10: "Louisville",
        week11: "Clemson",
        week12: "Wake Forest",
    },
    {
        team: "SMU",
        conference: "ACC",
        week1: "Florida State",
        week2: "FCS",
        week3: "Louisville",
        week4: "CUSA",
        week5: "Boston College",
        week6: "BYE",
        week7: "Virginia",
        week8: "California",
        week9: "Syracuse",
        week10: "Virginia Tech",
        week11: "Wake Forest",
        week12: "Notre Dame",
    },
    {
        team: "Syracuse",
        conference: "ACC",
        week1: "FCS",
        week2: "California",
        week3: "Pittsburgh",
        week4: "BYE",
        week5: "Independent",
        week6: "Virginia",
        week7: "Louisville",
        week8: "UNC",
        week9: "SMU",
        week10: "Clemson",
        week11: "NC State",
        week12: "Boston College",
    },
    {
        team: "UNC",
        conference: "ACC",
        week1: "TCU",
        week2: "FCS",
        week3: "Clemson",
        week4: "BYE",
        week5: "Notre Dame",
        week6: "Pittsburgh",
        week7: "Duke",
        week8: "Syracuse",
        week9: "Miami",
        week10: "Independent",
        week11: "Louisville",
        week12: "Virginia",
    },
    {
        team: "Stanford",
        conference: "ACC",
        week1: "Miami",
        week2: "BYE",
        week3: "Duke",
        week4: "Georgia Tech",
        week5: "Wake Forest",
        week6: "Notre Dame",
        week7: "FCS",
        week8: "NC State",
        week9: "Louisville",
        week10: "BYE",
        week11: "Virginia Tech",
        week12: "California",
    },
    {
        team: "Virginia",
        conference: "ACC",
        week1: "NC State",
        week2: "FCS",
        week3: "West Virginia",
        week4: "CUSA",
        week5: "Florida State",
        week6: "Syracuse",
        week7: "SMU",
        week8: "Duke",
        week9: "Wake Forest",
        week10: "BYE",
        week11: "California",
        week12: "UNC",
    },
    {
        team: "Clemson",
        conference: "ACC",
        week1: "LSU",
        week2: "Sun Belt",
        week3: "UNC",
        week4: "California",
        week5: "Miami",
        week6: "BYE",
        week7: "FCS",
        week8: "Virginia Tech",
        week9: "Florida State",
        week10: "Syracuse",
        week11: "Georgia Tech",
        week12: "Duke",
    },
    {
        team: "Pittsburgh",
        conference: "ACC",
        week1: "MAC",
        week2: "UCF",
        week3: "Syracuse",
        week4: "FCS",
        week5: "Virginia Tech",
        week6: "UNC",
        week7: "Boston College",
        week8: "Miami",
        week9: "Georgia Tech",
        week10: "BYE",
        week11: "Florida State",
        week12: "Louisville",
    },
    {
        team: "Duke",
        conference: "ACC",
        week1: "AAC",
        week2: "Illionis",
        week3: "Stanford",
        week4: "FCS",
        week5: "BYE",
        week6: "Georgia Tech",
        week7: "UNC",
        week8: "Virginia",
        week9: "Boston College",
        week10: "NC State",
        week11: "Miami",
        week12: "Clemson",
    },
    {
        team: "California",
        conference: "ACC",
        week1: "UCLA",
        week2: "Syracuse",
        week3: "FCS",
        week4: "Clemson",
        week5: "MW",
        week6: "Virginia Tech",
        week7: "Wake Forest",
        week8: "SMU",
        week9: "NC State",
        week10: "BYE",
        week11: "Virginia",
        week12: "Stanford",
    },
    {
        team: "Notre Dame",
        conference: "Independent",
        week1: "Wisconsin",
        week2: "FCS",
        week3: "Michigan State",
        week4: "Purdue",
        week5: "UNC",
        week6: "Stanford",
        week7: "BYU",
        week8: "BYE",
        week9: "AAC",
        week10: "Miami",
        week11: "Boston College",
        week12: "SMU",
    },
    {
        team: "Arizona State",
        conference: "Big 12",
        week1: "FCS",
        week2: "Texas A&M",
        week3: "Kansas",
        week4: "BYE",
        week5: "Baylor",
        week6: "MW",
        week7: "Texas Tech",
        week8: "Kansas State",
        week9: "BYE",
        week10: "Colorado",
        week11: "UCF",
        week12: "Oklahoma State",
    },
    {
        team: "Kansas State",
        conference: "Big 12",
        week1: "FCS",
        week2: "PAC12",
        week3: "AAC",
        week4: "Cincinnati",
        week5: "BYE",
        week6: "Houston",
        week7: "Kansas",
        week8: "Arizona State",
        week9: "Colorado",
        week10: "Oklahoma State",
        week11: "TCU",
        week12: "Arizona",
    },
    {
        team: "Texas Tech",
        conference: "Big 12",
        week1: "FCS",
        week2: "PAC12",
        week3: "Houston",
        week4: "CUSA",
        week5: "Colorado",
        week6: "BYE",
        week7: "Arizona State",
        week8: "Cincinnati",
        week9: "Arizona",
        week10: "West Virginia",
        week11: "Oklahoma State",
        week12: "Baylor",
    },
    {
        team: "Utah",
        conference: "Big 12",
        week1: "FCS",
        week2: "Arkansas",
        week3: "PAC12",
        week4: "Iowa State",
        week5: "BYE",
        week6: "Kansas",
        week7: "Colorado",
        week8: "Houston",
        week9: "Cincinnati",
        week10: "BYU",
        week11: "Arizona",
        week12: "TCU",
    },
    {
        team: "Houston",
        conference: "Big 12",
        week1: "PAC12",
        week2: "FCS",
        week3: "Texas Tech",
        week4: "Sun Belt",
        week5: "UCF",
        week6: "Kansas State",
        week7: "Oklahoma State",
        week8: "Utah",
        week9: "BYE",
        week10: "Cincinnati",
        week11: "Colorado",
        week12: "West Virginia",
    },
    {
        team: "Cincinnati",
        conference: "Big 12",
        week1: "Boston College",
        week2: "FCS",
        week3: "MAC",
        week4: "Kansas State",
        week5: "Arizona",
        week6: "BYE",
        week7: "West Virginia",
        week8: "Texas Tech",
        week9: "Utah",
        week10: "Houston",
        week11: "Iowa State",
        week12: "Colorado",
    },
    {
        team: "UCF",
        conference: "Big 12",
        week1: "FCS",
        week2: "Pittsburgh",
        week3: "Sun Belt",
        week4: "TCU",
        week5: "Houston",
        week6: "Oklahoma State",
        week7: "BYE",
        week8: "BYU",
        week9: "Baylor",
        week10: "Kansas",
        week11: "Arizona State",
        week12: "Iowa State",
    },
    {
        team: "BYU",
        conference: "Big 12",
        week1: "FCS",
        week2: "Arizona",
        week3: "MW",
        week4: "BYE",
        week5: "TCU",
        week6: "Iowa State",
        week7: "Notre Dame",
        week8: "UCF",
        week9: "Arizona State",
        week10: "Utah",
        week11: "Baylor",
        week12: "Kansas",
    },
    {
        team: "West Virginia",
        conference: "Big 12",
        week1: "Sun Belt",
        week2: "FCS",
        week3: "Virginia",
        week4: "Oklahoma State",
        week5: "Iowa State",
        week6: "Arizona",
        week7: "Cincinnati",
        week8: "TCU",
        week9: "BYE",
        week10: "Texas Tech",
        week11: "Kansas",
        week12: "Houston",
    },
    {
        team: "Baylor",
        conference: "Big 12",
        week1: "Auburn",
        week2: "FCS",
        week3: "CUSA",
        week4: "Colorado",
        week5: "Arizona State",
        week6: "BYE",
        week7: "TCU",
        week8: "Kansas",
        week9: "UCF",
        week10: "Iowa State",
        week11: "BYU",
        week12: "Texas Tech",
    },
    {
        team: "Arizona",
        conference: "Big 12",
        week1: "FCS",
        week2: "BYU",
        week3: "MAC",
        week4: "PAC12",
        week5: "Cincinnati",
        week6: "West Virginia",
        week7: "BYE",
        week8: "Iowa State",
        week9: "Texas Tech",
        week10: "TCU",
        week11: "Utah",
        week12: "Kansas State",
    },
    {
        team: "TCU",
        conference: "Big 12",
        week1: "UNC",
        week2: "FCS",
        week3: "Sun Belt",
        week4: "UCF",
        week5: "BYU",
        week6: "BYE",
        week7: "Baylor",
        week8: "West Virginia",
        week9: "Kansas",
        week10: "Arizona",
        week11: "Kansas State",
        week12: "Utah",
    },
    {
        team: "Colorado",
        conference: "Big 12",
        week1: "Georgia Tech",
        week2: "FCS",
        week3: "Northwestern",
        week4: "Baylor",
        week5: "Texas Tech",
        week6: "BYE",
        week7: "Utah",
        week8: "Oklahoma State",
        week9: "Kansas State",
        week10: "Arizona State",
        week11: "Houston",
        week12: "Cincinnati",
    },
    {
        team: "Kansas",
        conference: "Big 12",
        week1: "FCS",
        week2: "Missouri",
        week3: "Arizona State",
        week4: "BYE",
        week5: "CUSA",
        week6: "Utah",
        week7: "Kansas State",
        week8: "Kansas",
        week9: "TCU",
        week10: "Baylor",
        week11: "West Virginia",
        week12: "BYU",
    },
    {
        team: "Iowa State",
        conference: "Big 12",
        week1: "FCS",
        week2: "Iowa",
        week3: "MAC",
        week4: "Utah",
        week5: "West Virginia",
        week6: "BYU",
        week7: "BYE",
        week8: "Arizona",
        week9: "Oklahoma State",
        week10: "Baylor",
        week11: "Cincinnati",
        week12: "UCF",
    },
    {
        team: "Oklahoma State",
        conference: "Big 12",
        week1: "CUSA",
        week2: "Oregon",
        week3: "FCS",
        week4: "West Virginia",
        week5: "BYE",
        week6: "UCF",
        week7: "Houston",
        week8: "Colorado",
        week9: "Iowa State",
        week10: "Kansas State",
        week11: "Oklahoma State",
        week12: "Arizona State",
    },
    {
        team: "Michigan State",
        conference: "Big Ten",
        week1: "MAC",
        week2: "MAC",
        week3: "Notre Dame",
        week4: "Nebraska",
        week5: "Wisconsin",
        week6: "Illinois",
        week7: "Northwestern",
        week8: "UCLA",
        week9: "BYE",
        week10: "Michigan",
        week11: "Washington",
        week12: "Oregon",
    },
    {
        team: "Illinois",
        conference: "Big Ten",
        week1: "AAC",
        week2: "Duke",
        week3: "FCS",
        week4: "Ohio State",
        week5: "Purdue",
        week6: "Michigan State",
        week7: "BYE",
        week8: "Oregon",
        week9: "Maryland",
        week10: "Nebraska",
        week11: "UCLA",
        week12: "Iowa",
    },
    {
        team: "UCLA",
        conference: "Big Ten",
        week1: "California",
        week2: "PAC 12",
        week3: "Purdue",
        week4: "Maryland",
        week5: "BYE",
        week6: "Oregon",
        week7: "Wisconsin",
        week8: "Michigan State",
        week9: "MW",
        week10: "Minnesota",
        week11: "Illinois",
        week12: "Michigan",
    },
    {
        team: "Purdue",
        conference: "Big Ten",
        week1: "FCS",
        week2: "Wake Forest",
        week3: "UCLA",
        week4: "Notre Dame",
        week5: "Illinois",
        week6: "Minnesota",
        week7: "Washington",
        week8: "BYE",
        week9: "Penn State",
        week10: "Maryland",
        week11: "Iowa",
        week12: "Wisconsin",
    },
    {
        team: "Oregon",
        conference: "Big Ten",
        week1: "PAC 12",
        week2: "Oklahoma State",
        week3: "FCS",
        week4: "USC",
        week5: "BYE",
        week6: "UCLA",
        week7: "Nebraska",
        week8: "Illinois",
        week9: "Northwestern",
        week10: "Ohio State",
        week11: "Michigan",
        week12: "Michigan State",
    },
    {
        team: "Minnesota",
        conference: "Big Ten",
        week1: "FCS",
        week2: "Mississippi State",
        week3: "MAC",
        week4: "Washington",
        week5: "Michigan",
        week6: "Purdue",
        week7: "BYE",
        week8: "Iowa",
        week9: "Indiana",
        week10: "UCLA",
        week11: "Penn State",
        week12: "Northwestern",
    },
    {
        team: "Washington",
        conference: "Big Ten",
        week1: "PAC12",
        week2: "PAC12",
        week3: "FCS",
        week4: "Minnesota",
        week5: "UCS",
        week6: "Iowa",
        week7: "Purdue",
        week8: "BYE",
        week9: "Nebraska",
        week10: "Penn State",
        week11: "Michigan State",
        week12: "Indiana",
    },
    {
        team: "Wisconsin",
        conference: "Big Ten",
        week1: "Notre Dame",
        week2: "FCS",
        week3: "MAC",
        week4: "Penn State",
        week5: "Michigan State",
        week6: "BYE",
        week7: "UCLA",
        week8: "USC",
        week9: "Iowa",
        week10: "Rutgers",
        week11: "Maryland",
        week12: "Purdue",
    },
    {
        team: "Northwestern",
        conference: "Big Ten",
        week1: "FCS",
        week2: "BYE",
        week3: "Colorado",
        week4: "Indiana",
        week5: "Penn State",
        week6: "FCS",
        week7: "Michigan State",
        week8: "Rutgers",
        week9: "Oregon",
        week10: "Iowa",
        week11: "Ohio State",
        week12: "Minnesota",
    },
    {
        team: "USC",
        conference: "Big Ten",
        week1: "Sun Belt",
        week2: "PAC 12",
        week3: "Sun Belt",
        week4: "Rutgers",
        week5: "Oregon",
        week6: "Washington",
        week7: "Penn State",
        week8: "BYE",
        week9: "Wisconsin",
        week10: "Ohio State",
        week11: "Indiana",
        week12: "Maryland",
    },
    {
        team: "Nebraska",
        conference: "Big Ten",
        week1: "MAC",
        week2: "MAC",
        week3: "FCS",
        week4: "Michigan State",
        week5: "Maryland",
        week6: "Indiana",
        week7: "Oregon",
        week8: "BYE",
        week9: "Washington",
        week10: "Illinois",
        week11: "Rutgers",
        week12: "Ohio State",
    },
    {
        team: "Ohio State",
        conference: "Big Ten",
        week1: "FCS",
        week2: "Texas",
        week3: "MAC",
        week4: "Illinois",
        week5: "Iowa",
        week6: "Maryland",
        week7: "Indiana",
        week8: "BYE",
        week9: "USC",
        week10: "Oregon",
        week11: "Northwestern",
        week12: "Nebraska",
    },
    {
        team: "Iowa",
        conference: "Big Ten",
        week1: "MAC",
        week2: "Iowa State",
        week3: "FCS",
        week4: "Michigan",
        week5: "Ohio State",
        week6: "Washington",
        week7: "BYE",
        week8: "Minnesota",
        week9: "Wisconsin",
        week10: "Northwestern",
        week11: "Purdue",
        week12: "Illinois",
    },
    {
        team: "Rutgers",
        conference: "Big Ten",
        week1: "MAC",
        week2: "Boston College",
        week3: "USC",
        week4: "FCS",
        week5: "Indiana",
        week6: "BYE",
        week7: "Maryland",
        week8: "Northwestern",
        week9: "Michigan",
        week10: "Wisconsin",
        week11: "Nebraska",
        week12: "Penn State",
    },
    {
        team: "Michigan",
        conference: "Big Ten",
        week1: "MAC",
        week2: "Oklahoma",
        week3: "MW",
        week4: "Iowa",
        week5: "Minnesota",
        week6: "BYE",
        week7: "Penn State",
        week8: "Indiana",
        week9: "Rutgers",
        week10: "Michigan State",
        week11: "Oregon",
        week12: "UCLA",
    },
    {
        team: "Maryland",
        conference: "Big Ten",
        week1: "FCS",
        week2: "Independent",
        week3: "Virginia Tech",
        week4: "UCLA",
        week5: "Nebraska",
        week6: "Ohio State",
        week7: "Rutgers",
        week8: "BYE",
        week9: "Illinois",
        week10: "Purdue",
        week11: "Wisconsin",
        week12: "USC",
    },
    {
        team: "Penn State",
        conference: "Big Ten",
        week1: "Sun Belt",
        week2: "AAC",
        week3: "MAC",
        week4: "Wisconsin",
        week5: "Northwestern",
        week6: "USC",
        week7: "Michigan",
        week8: "BYE",
        week9: "Purdue",
        week10: "Washington",
        week11: "Minnesota",
        week12: "Rutgers",
    },
    {
        team: "Indiana",
        conference: "Big Ten",
        week1: "FCS",
        week2: "FCS",
        week3: "CUSA",
        week4: "Northwestern",
        week5: "Rutgers",
        week6: "Nebraska",
        week7: "Ohio State",
        week8: "Michigan",
        week9: "Minnesota",
        week10: "BYE",
        week11: "USC",
        week12: "Washington",
    },
    {
        team: "Alabama",
        conference: "SEC",
        week1: "CUSA",
        week2: "Kentucky",
        week3: "Florida State",
        week4: "South Carolina",
        week5: "Mississippi State",
        week6: "Georgia",
        week7: "Tennessee",
        week8: "Texas A&M",
        week9: "BYE",
        week10: "LSU",
        week11: "Vanderbilt",
        week12: "FCS",
    },
    {
        team: "Oklahoma",
        conference: "SEC",
        week1: "MW",
        week2: "Michigan",
        week3: "Sun Belt",
        week4: "Georgia",
        week5: "BYE",
        week6: "Texas",
        week7: "Kentucky",
        week8: "Mississippi State",
        week9: "South Carolina",
        week10: "Florida",
        week11: "Ole Miss",
        week12: "Texas A&M",
    },
    {
        team: "Georgia",
        conference: "SEC",
        week1: "FCS",
        week2: "CUSA",
        week3: "Arkansas",
        week4: "Oklahoma",
        week5: "Vanderbilt",
        week6: "Alabama",
        week7: "Auburn",
        week8: "BYE",
        week9: "Florida",
        week10: "Ole Miss",
        week11: "Missouri",
        week12: "South Carolina",
    },
    {
        team: "Kentucky",
        conference: "SEC",
        week1: "FCS",
        week2: "Alabama",
        week3: "Texas A&M",
        week4: "Sun Belt",
        week5: "South Carolina",
        week6: "LSU",
        week7: "Oklahoma",
        week8: "Vanderbilt",
        week9: "BYE",
        week10: "Tennessee",
        week11: "Florida",
        week12: "Missouri",
    },
    {
        team: "Mississippi State",
        conference: "SEC",
        week1: "Sun Belt",
        week2: "Minnesota",
        week3: "South Carolina",
        week4: "Missouri",
        week5: "Alabama",
        week6: "BYE",
        week7: "LSU",
        week8: "Oklahoma",
        week9: "Texas",
        week10: "Vanderbilt",
        week11: "Auburn",
        week12: "FCS",
    },
    {
        team: "Missouri",
        conference: "SEC",
        week1: "FCS",
        week2: "Kansas",
        week3: "Sun Belt",
        week4: "Mississippi State",
        week5: "Florida",
        week6: "Texas A&M",
        week7: "Ole Miss",
        week8: "BYE",
        week9: "Arkansas",
        week10: "Texas",
        week11: "Georgia",
        week12: "Kentucky",
    },
    {
        team: "South Carolina",
        conference: "SEC",
        week1: "CUSA",
        week2: "FCS",
        week3: "Mississippi State",
        week4: "Alabama",
        week5: "Kentucky",
        week6: "Florida",
        week7: "BYE",
        week8: "Tennessee",
        week9: "Oklahoma",
        week10: "South Carolina",
        week11: "Arkansas",
        week12: "Georgia",
    },
    {
        team: "Vanderbilt",
        conference: "SEC",
        week1: "FCS",
        week2: "CUSA",
        week3: "NC State",
        week4: "Auburn",
        week5: "Georgia",
        week6: "Ole Miss",
        week7: "Arkansas",
        week8: "Kentucky",
        week9: "BYE",
        week10: "Mississippi State",
        week11: "Alabama",
        week12: "Florida",
    },
    {
        team: "Tennessee",
        conference: "SEC",
        week1: "FCS",
        week2: "Georgia Tech",
        week3: "CUSA",
        week4: "Texas",
        week5: "Auburn",
        week6: "Arkansas",
        week7: "Alabama",
        week8: "South Carolina",
        week9: "BYE",
        week10: "Kentucky",
        week11: "Texas A&M",
        week12: "LSU",
    },
    {
        team: "Texas",
        conference: "SEC",
        week1: "PAC 12",
        week2: "Ohio State",
        week3: "MW",
        week4: "Tennessee",
        week5: "BYE",
        week6: "Oklahoma",
        week7: "Florida",
        week8: "Ole Miss",
        week9: "Mississippi State",
        week10: "Missouri",
        week11: "LSU",
        week12: "Arkansas",
    },
    {
        team: "Florida",
        conference: "SEC",
        week1: "AAC",
        week2: "FCS",
        week3: "Auburn",
        week4: "Ole Miss",
        week5: "Missouri",
        week6: "South Carolina",
        week7: "Texas",
        week8: "BYE",
        week9: "Georgia",
        week10: "Oklahoma",
        week11: "Kentucky",
        week12: "Vanderbilt",
    },
    {
        team: "Texas A&M",
        conference: "SEC",
        week1: "CUSA",
        week2: "Arizona State",
        week3: "Kentucky",
        week4: "LSU",
        week5: "Arkansas",
        week6: "Missouri",
        week7: "FCS",
        week8: "Alabama",
        week9: "BYE",
        week10: "South Carolina",
        week11: "Tennessee",
        week12: "Oklahoma",
    },
    {
        team: "Ole Miss",
        conference: "SEC",
        week1: "Louisville",
        week2: "AAC",
        week3: "LSU",
        week4: "Florida",
        week5: "BYE",
        week6: "Vanderbilt",
        week7: "Missouri",
        week8: "Texas",
        week9: "Auburn",
        week10: "Georgia",
        week11: "Oklahoma",
        week12: "FCS",
    },
    {
        team: "Auburn",
        conference: "SEC",
        week1: "Baylor",
        week2: "Sun Belt",
        week3: "Florida",
        week4: "Vanderbilt",
        week5: "Tennessee",
        week6: "BYE",
        week7: "Georgia",
        week8: "LSU",
        week9: "Ole Miss",
        week10: "Arkansas",
        week11: "Mississippi State",
        week12: "FCS",
    },
    {
        team: "LSU",
        conference: "SEC",
        week1: "Clemson",
        week2: "Sun Belt",
        week3: "Ole Miss",
        week4: "Texas A&M",
        week5: "FCS",
        week6: "Kentucky",
        week7: "Mississippi State",
        week8: "Auburn",
        week9: "BYE",
        week10: "Alabama",
        week11: "Texas",
        week12: "Tennessee",
    },
]