export type Schedule = {
    team: string;
    conference: string;
    week1?: string;
    week2?: string;
    week3?: string;
    week4?: string;
    week5?: string;
    week6?: string;
    week7?: string;
    week8?: string;
    week9?: string;
    week10?: string;
    week11?: string;
    week12?: string;
}

export const schedules: Schedule[] = [
    {
        team: "NC State",
        conference: "ACC",
        week1: "Virginia",
        week2: "FCS",
        week3: "Vanderbilt",
        week4: "App State",
        week5: "Louisville",
        week6: "Wake Forest",
        week7: "BYE",
        week8: "Stanford",
        week9: "California",
        week10: "Duke",
        week11: "Syracuse",
        week12: "Florida State",
    },
    {
        team: "Florida State",
        conference: "ACC",
        week1: "SMU",
        week2: "BYE",
        week3: "Alabama",
        week4: "FCS",
        week5: "Virginia",
        week6: "Louisville",
        week7: "Miami FL",
        week8: "BYE",
        week9: "Clemson",
        week10: "Boston College",
        week11: "Pittsburgh",
        week12: "NC State",
    },
    {
        team: "Louisville",
        conference: "ACC",
        week1: "Mississippi",
        week2: "FCS",
        week3: "SMU",
        week4: "Wake Forest",
        week5: "NC State",
        week6: "Florida State",
        week7: "Syracuse",
        week8: "BYE",
        week9: "Stanford",
        week10: "Georgia Tech",
        week11: "UNC",
        week12: "Pittsburgh",
    },
    {
        team: "Boston College",
        conference: "ACC",
        week1: "Cincinnati",
        week2: "Rutgers",
        week3: "FCS",
        week4: "Virginia Tech",
        week5: "SMU",
        week6: "BYE",
        week7: "Pittsburgh",
        week8: "Georgia Tech",
        week9: "Duke",
        week10: "Florida State",
        week11: "Notre Dame",
        week12: "Syracuse",
    },
    {
        team: "Miami",
        conference: "ACC",
        week1: "Stanford",
        week2: "FCS",
        week3: "Wake Forest",
        week4: "MAC",
        week5: "Clemson",
        week6: "BYE",
        week7: "Florida State",
        week8: "Pittsburgh",
        week9: "UNC",
        week10: "Notre Dame",
        week11: "Duke",
        week12: "Virginia Tech",
    },
    {
        team: "Wake Forest",
        conference: "ACC",
        week1: "FCS",
        week2: "Purdue",
        week3: "Miami",
        week4: "Louisville",
        week5: "Stanford",
        week6: "NC State",
        week7: "California",
        week8: "BYE",
        week9: "Virginia",
        week10: "FCS",
        week11: "SMU",
        week12: "Georgia Tech",
    },
    {
        team: "Virginia Tech",
        conference: "ACC",
        week1: "FCS",
        week2: "Sun Belt",
        week3: "Maryland",
        week4: "Boston College",
        week5: "Pittsburgh",
        week6: "California",
        week7: "Georgia Tech",
        week8: "Clemson",
        week9: "BYE",
        week10: "SMU",
        week11: "Stanford",
        week12: "Miami",
    },
    {
        team: "Georgia Tech",
        conference: "ACC",
        week1: "Colorado",
        week2: "Tennessee",
        week3: "FCS",
        week4: "Stanford",
        week5: "BYE",
        week6: "Duke",
        week7: "Virginia Tech",
        week8: "Boston College",
        week9: "Pittsburgh",
        week10: "Louisville",
        week11: "Clemson",
        week12: "Wake Forest",
    },
    {
        team: "SMU",
        conference: "ACC",
        week1: "Florida State",
        week2: "FCS",
        week3: "Louisville",
        week4: "CUSA",
        week5: "Boston College",
        week6: "BYE",
        week7: "Virginia",
        week8: "California",
        week9: "Syracuse",
        week10: "Virginia Tech",
        week11: "Wake Forest",
        week12: "Notre Dame",
    },
    {
        team: "Syracuse",
        conference: "ACC",
        week1: "FCS",
        week2: "California",
        week3: "Pittsburgh",
        week4: "BYE",
        week5: "Independent",
        week6: "Virginia",
        week7: "Louisville",
        week8: "UNC",
        week9: "SMU",
        week10: "Clemson",
        week11: "NC State",
        week12: "Boston College",
    },
    {
        team: "UNC",
        conference: "ACC",
        week1: "TCU",
        week2: "FCS",
        week3: "Clemson",
        week4: "BYE",
        week5: "Notre Dame",
        week6: "Pittsburgh",
        week7: "Duke",
        week8: "Syracuse",
        week9: "Miami",
        week10: "Independent",
        week11: "Louisville",
        week12: "Virginia",
    },
    {
        team: "Stanford",
        conference: "ACC",
        week1: "Miami",
        week2: "BYE",
        week3: "Duke",
        week4: "Georgia Tech",
        week5: "Wake Forest",
        week6: "Notre Dame",
        week7: "FCS",
        week8: "NC State",
        week9: "Louisville",
        week10: "BYE",
        week11: "Virginia Tech",
        week12: "California",
    },
    {
        team: "Virginia",
        conference: "ACC",
        week1: "NC State",
        week2: "FCS",
        week3: "West Virginia",
        week4: "CUSA",
        week5: "Florida State",
        week6: "Syracuse",
        week7: "SMU",
        week8: "Duke",
        week9: "Wake Forest",
        week10: "BYE",
        week11: "California",
        week12: "UNC",
    },
    {
        team: "Clemson",
        conference: "ACC",
        week1: "LSU",
        week2: "Sun Belt",
        week3: "UNC",
        week4: "California",
        week5: "Miami",
        week6: "BYE",
        week7: "FCS",
        week8: "Virginia Tech",
        week9: "Florida State",
        week10: "Syracuse",
        week11: "Georgia Tech",
        week12: "Duke",
    },
    {
        team: "Pittsburgh",
        conference: "ACC",
        week1: "MAC",
        week2: "UCF",
        week3: "Syracuse",
        week4: "FCS",
        week5: "Virginia Tech",
        week6: "UNC",
        week7: "Boston College",
        week8: "Miami",
        week9: "Georgia Tech",
        week10: "BYE",
        week11: "Florida State",
        week12: "Louisville",
    },
    {
        team: "Duke",
        conference: "ACC",
        week1: "AAC",
        week2: "Illionis",
        week3: "Stanford",
        week4: "FCS",
        week5: "BYE",
        week6: "Georgia Tech",
        week7: "UNC",
        week8: "Virginia",
        week9: "Boston College",
        week10: "NC State",
        week11: "Miami",
        week12: "Clemson",
    },
    {
        team: "California",
        conference: "ACC",
        week1: "UCLA",
        week2: "Syracuse",
        week3: "FCS",
        week4: "Clemson",
        week5: "MW",
        week6: "Virginia Tech",
        week7: "Wake Forest",
        week8: "SMU",
        week9: "NC State",
        week10: "BYE",
        week11: "Virginia",
        week12: "Stanford",
    },
    {
        team: "Notre Dame",
        conference: "Independent",
        week1: "Wisconsin",
        week2: "FCS",
        week3: "Michigan State",
        week4: "Purdue",
        week5: "UNC",
        week6: "Stanford",
        week7: "BYU",
        week8: "BYE",
        week9: "AAC",
        week10: "Miami",
        week11: "Boston College",
        week12: "SMU",
    },
    {
        team: "Arizona State",
        conference: "Big 12",
        week1: "FCS",
        week2: "Texas A&M",
        week3: "Kansas",
        week4: "BYE",
        week5: "Baylor",
        week6: "MW",
        week7: "Texas Tech",
        week8: "Kansas State",
        week9: "BYE",
        week10: "Colorado",
        week11: "UCF",
        week12: "Oklahoma State",
    },
]